name: Pull request java-parent

on:
  pull_request:
    branches: [main]

jobs:
  pr-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
      - name: Maven verify
        run: ./mvnw -B -ntp verify -f pom.xml
