name: Build java-parent

on:
  push:
    branches: [main]
    paths:
      - "pom.xml"
      - ".github/workflows/push.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          server-id: github
          settings-path: ${{ github.workspace }}
          cache: "maven"
      - run: less $GITHUB_WORKSPACE/settings.xml
      - name: Update version
        run: ./mvnw -B -ntp versions:set -DnewVersion=$GITHUB_RUN_NUMBER -f pom.xml
      - name: Build with Maven
        run: ./mvnw -B -ntp verify -f pom.xml
      - name: Upload java-parent artifact
        uses: actions/upload-artifact@v4
        with:
          name: java-parent
          path: pom.xml
